config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  #delete通信のはずなのに、getがないとエラーがおきてしまうので追加
  #devise_scope :user do
    # link_toで　method: :deleteを:destroyと勘違いしてしまっていたので注意
    # get '/users/sign_out' => 'devise/sessions#destroy'
    # post '/users/sign_out' => 'devise/sessions#destroy'
  #end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "articles#index"

  #リソースベースのルーティング（z以下リソースルーティング）を使うことで、指定のリソースコントローラでよく使われるすべてのルーティングを手軽に宣言できます。
  #resourcesを宣言するだけで、コントローラのindex、show、new、edit、create、update、destroyアクションを個別に宣言しなくても1行で宣言が完了します。
  resources :articles, param: :uuid do
    member do
      get :toggle_like
      post :toggle_like
    end
  end

  resources :categories, only: [:index] do
    collection do
      get :select
    end
  end
  resources :subcategories, only: [:show] do
    collection do
      get :select
    end
  end
  resources :messages, only: [:create]
  resources :rooms, param: :uuid, only: [:create, :show]

  resources :users, param: :uuid, only: [:index, :show, :update] do
    member do
      get :followings, :followers
    end
    resource :relationships, only: [:create, :destroy] do
      get :create
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  before_create :generate_uuid

  def to_param
      uuid
  end

  belongs_to :user
  belongs_to :subcategory
  has_many :likes, dependent: :destroy
  has_one_attached :image, dependent: :destroy 
  
  validates :title, presence: true
  validates :content, presence: true

  #scope :featured, -> (count = 10) { where(featured: true).order(created_at: :desc).limit(count) }

  private

  def generate_uuid
    self.uuid = SecureRandom.hex(8)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :authenticate_user!, only: [:new, :update, :create, :destroy]

    def index
        @featured_articles = Article.includes(:user).where(featured: true).order(id: :desc).limit(4)
        
        @followings_articles = []

        if user_signed_in?
            # フォローしているユーザーのIDを取得
            following_ids = current_user.followings.pluck(:id)

            # フォローしているユーザーの記事を取得し、関連情報をプリロード
            @followings_articles = Article.where(user_id: following_ids).order(id: :desc).limit(4)
        end
    end

    def new
    end

    def edit
        @article = Article.find_by(uuid: params[:uuid])
    end

    def update
        article = Article.find_by(uuid: params[:uuid])
        if current_user.id == article.user_id
            article.update(update_articles_params)
        end
        redirect_to root_path
    end

    def create
        article = Article.create(create_articles_params)
        if article.valid?
            redirect_to select_categories_path(uuid: article.uuid)
        else
            redirect_back(fallback_location: root_path)
        end
    end

    def destroy
        article = Article.find_by(uuid: params[:uuid])
        article.destroy
        redirect_to root_path
    end

    def show
        @article = Article.includes(image_attachment: :blob).find_by(uuid: params[:uuid])
    end

    def toggle_like
        if user_signed_in?
            article = Article.find_by(uuid: params[:uuid])
            like = article.likes.find_by(user_id: current_user.id)
            if like
                like.destroy
            else
                Like.create(user_id: current_user.id, article_id: article.id)
            end
            redirect_back(fallback_location: root_path)
        else
            redirect_to new_user_session_path
        end
    end

    private

    def create_articles_params
        params.require(:article).permit(:title, :content, :image, :linkurl).merge(user_id: current_user.id, featured: true, subcategory_id: 1)
    end

    def update_articles_params
        params.require(:article).permit(:title, :content, :image, :linkurl, :subcategory_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article_card.html.erb
<div class="col-12 col-md-6 col-lg-4 col-xl-3">
  <div class="mb-4 px-2 article-card">
    <div class="card">
      <%= link_to article_path(article), class:"article-link" do %>
      <% if article.image.present? %>
        <%= image_tag article.image.variant(resize_to_limit: [160, 90]).processed, class:"card-img-top", alt: "エラー"%>
      <% else %>
        <%= image_tag "160x90.png", size: "160x90" , class:"card-img-top", alt: "エラー" %>
      <% end %>
      <div class="card-body">
        <p class="card-text fw-bolder text-truncate"><%= article.title %></p>
        <br>
        <div class="d-flex justify-content-between fw-light">
          <div class="d-flex">
            <% if article.user.avatar.attached? %>
              <%= image_tag article.user.avatar.variant(resize_to_limit: [24, 24]), class:"rounded-circle me-2" %>
            <% else %>
              <%= image_tag "default_icon.png", size:"24x24", class:"rounded-circle me-2" %>
            <% end %>
            <%= article.user.username %>
          </div>
          <span class=""><%= time_ago_in_words(article.created_at) %>前</span>
        </div>
      </div>
      <% end %>
      <div class="d-flex justify-content-left ms-3">
        <%= link_to toggle_like_article_path(article), data: { "turbo-method": :post }, class:"article-link cursor-pointer" do %>
          <%= image_tag "Heart.png", size:"20x20" %>
        <% end %>
        <span class="ms-1"><%= article.likes_count %></span>
      </div>
    </div>
  </div>
</div>

app/views/articles/_mockup_article_card.html.erb
<div class="col-12 col-md-6 col-lg-4 col-xl-3">
  <div class="mb-4 px-2 article-card">
    <div class="card">
      <%= link_to article_path(article), class:"article-link" do %>
      <% if article.image.present? %>
        <%= image_tag article.image.variant(resize_to_limit: [160, 90]).processed, class:"card-img-top", alt: "エラー"%>
      <% else %>
        <%= image_tag "160x90.png", size: "160x90" , class:"card-img-top", alt: "エラー" %>
      <% end %>
      <div class="card-body">
        <p class="card-text fw-bolder text-truncate"><%= article.title %></p>
        <br>
        <div class="d-flex justify-content-between fw-light">
          <div class="d-flex">
            <% if article.user.avatar.attached? %>
              <%= image_tag article.user.avatar.variant(resize_to_limit: [24, 24]), class:"rounded-circle me-2" %>
            <% else %>
              <%= image_tag "default_icon.png", size:"24x24", class:"rounded-circle me-2" %>
            <% end %>
            <%= article.user.username %>
          </div>
          <span class=""><%= time_ago_in_words(article.created_at) %>前</span>
        </div>
      </div>
      <% end %>
      <div class="d-flex justify-content-left ms-3">
        <%= button_to toggle_like_article_path(article), data: { "turbo-method": :post }, class:"article-link" do %>
          <%= image_tag "Heart.png", size:"20x20" %>
        <% end %>
        <span class="ms-1"><%= article.likes_count %></span>
      </div>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h3 class="mb-3">記事の作成</h3>
<%= form_with model: @article, scope: :article, local: true do |f| %>
  <label class="block size-full">
    <%= f.file_field :image, id:"file-input", class: "d-none" %>
    <!-- クリック可能な画像 -->
    <label for="file-input" style="cursor: pointer;">
      <% if @article.image.attached? %>
        <%= image_tag @article.image, id: "preview-image", class: "img-thumbnail vw-100 vh-25" %>
      <% else %>
        <%= image_tag "160x90.png", id: "preview-image", class: "img-thumbnail vw-100 vh-25" %>
      <% end %>
    </label>
  </label>
  <%= f.label :title, "タイトル" %>
  <%= f.text_field :title, class: "form-control me-2" %>
  <%= f.label :content, "コンテンツ" %>
  <%= f.text_area :content, class: "form-control me-2", size:"50x8", maxlength: "400"%>
  <%= f.label :linkurl, "URL" %>
  <%= f.url_field :linkurl, class: "form-control me-2" %>
  <%= f.submit "保存", class: "btn btn-outline-primary"%>
<% end %>
<script>
document.addEventListener("DOMContentLoaded", () => {
  const fileInput = document.getElementById("file-input");
  const previewImage = document.getElementById("preview-image");

  fileInput.addEventListener("change", (event) => {
    const file = event.target.files[0];
    if (file) {
      const reader = new FileReader();

      reader.onload = (e) => {
        previewImage.src = e.target.result;
      };

      reader.readAsDataURL(file);
    }
  });
});
</script>

app/views/articles/index.html.erb
<h3 class="mb-3">今日の注目記事</h3>
<div class="row card-container">
  <%= render partial: "/articles/article_card", 
          collection: @featured_articles, 
          as: :article %>
  <!-- 他のカードも追加可能 -->
</div>
<% unless @followings_articles.empty? %>
  <h3 class="mb-3">フォロワーの注目記事</h3>
  <div class="row card-container">
  <%= render partial: "/articles/article_card", 
          collection: @followings_articles, 
          as: :article %>
  <!-- 他のカードも追加可能 -->
  </div>
<% end %>
<script>
  function adjustCards() {
    const containers = document.querySelectorAll(".card-container");

    // ウィンドウ幅に応じたカード数
    let visibleCards = 1;
    if (window.innerWidth >= 768) visibleCards = 2; // 中画面なら2枚
    if (window.innerWidth >= 1024) visibleCards = 3; // 大画面なら3枚
    if (window.innerWidth >= 1200) visibleCards = 4; // 大画面なら3枚

    // 各コンテナに対して処理を実行
    containers.forEach(container => {
      const cards = container.querySelectorAll(".article-card"); // コンテナ内のカードを取得

      // カードを表示/非表示に切り替える
      cards.forEach((card, index) => {
        card.style.display = index < visibleCards ? "block" : "none";
      });
    });
  }

  // 初回実行
  adjustCards();

  // ウィンドウサイズ変更時に実行
  window.addEventListener("resize", adjustCards);
</script>

app/views/articles/mockup.html.erb
<h3 class="mb-3">今日の注目記事</h3>
<div class="row card-container">
  <%= render partial: "/articles/mockup_article_card", 
          collection: @featured_articles, 
          as: :article %>
  <!-- 他のカードも追加可能 -->
</div>
<% unless @followings_articles.empty? %>
  <h3 class="mb-3">フォロワーの注目記事</h3>
  <div class="row card-container">
  <%= render partial: "/articles/mockup_article_card", 
          collection: @followings_articles, 
          as: :article %>
  <!-- 他のカードも追加可能 -->
  </div>
<% end %>
<script>
  function adjustCards() {
    const containers = document.querySelectorAll('.card-container');

    // ウィンドウ幅に応じたカード数
    let visibleCards = 1;
    if (window.innerWidth >= 768) visibleCards = 2; // 中画面なら2枚
    if (window.innerWidth >= 1024) visibleCards = 3; // 大画面なら3枚
    if (window.innerWidth >= 1200) visibleCards = 4; // 大画面なら3枚

    // 各コンテナに対して処理を実行
    containers.forEach(container => {
      const cards = container.querySelectorAll('.article-card'); // コンテナ内のカードを取得

      // カードを表示/非表示に切り替える
      cards.forEach((card, index) => {
        card.style.display = index < visibleCards ? 'block' : 'none';
      });
    });
  }

  // 初回実行
  adjustCards();

  // ウィンドウサイズ変更時に実行
  window.addEventListener('resize', adjustCards);
</script>

app/views/articles/new.html.erb
<h3 class="mb-3">記事の作成</h3>
<%= form_with url: articles_path, scope: :article, local: true do |f| %>
  <label class="block size-full">
    <%= f.file_field :image, id:"file-input", class: "d-none" %>
    <!-- クリック可能な画像 -->
    <label for="file-input" style="cursor: pointer;">
      <%= image_tag "160x90.png", id: "preview-image", class: "img-thumbnail vw-100 vh-25" %>
    </label>
  </label>
  <%= f.label :title, "タイトル" %>
  <%= f.text_field :title, class: "form-control me-2" %>
  <%= f.label :content, "コンテンツ" %>
  <%= f.text_area :content, class: "form-control me-2", size:"50x8", maxlength: "400"%>
  <%= f.label :linkurl, "URL" %>
  <%= f.url_field :linkurl, class: "form-control me-2" %>
  <%= f.submit "作成", class: "btn btn-outline-primary"%>
<% end %>
<script>
document.addEventListener("DOMContentLoaded", () => {
  const fileInput = document.getElementById("file-input");
  const previewImage = document.getElementById("preview-image");

  fileInput.addEventListener("change", (event) => {
    const file = event.target.files[0];
    if (file) {
      const reader = new FileReader();

      reader.onload = (e) => {
        previewImage.src = e.target.result;
      };

      reader.readAsDataURL(file);
    }
  });
});
</script>

app/views/articles/show.html.erb
<div class="fs-lg">
  <%= @article.title %>
</div>
<br>
<div>
  <%= @article.content %>
</div>
<br>
<div>
  <%= @article.subcategory.category.name %>
</div>
<br>
<div>
  <%= @article.subcategory.name %>
</div>
<br>
<!-- 別タブで開く target: :_blank, rel: "noopener noreferrer" -->
<div>
<%= link_to @article.linkurl, @article.linkurl, target: :_blank, rel: "noopener noreferrer"%>
</div>

<% if user_signed_in? && current_user.id == @article.user_id %>
  <br>
  <%= button_to "編集", edit_article_path, method: :get, class:"btn btn-secondary" %>
  <%= button_to "削除", article_path, method: :delete, class:"btn btn-danger" %>
<% end %>

app/views/articles/signup.erb
<p>signup</p>

app/views/articles/write.html.erb
<div class="container my-4">
  <!-- ヘッダー -->
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h1><%= link_to "I T", "/articles/mockup" %></h1>

    <!-- 検索フォーム -->
    
    <input type="text" class="form-control d-flex me-2 w-50" placeholder="キーワードやクリエイターで検索" name="keyword">
    <%= link_to '検索', root_path, class: 'btn btn-primary' %>

    <div class="d-flex">
      <% if user_signed_in? %>
        <button type="button" class="btn dropdown-toggle border-white text-white" id="dropdownMenu" data-bs-toggle="dropdown" data-bs-offset="-50, 0" data-bs-auto-close="outside" aria-expaneded="false">
          <%= image_tag "default_icon.png", class:"rounded-circle", alt:"メニュー", size:"32x32"%>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu">
          <li class="">
            <div class="row">
              <div class="col ms-3 mt-1 clearfix">
                <%= image_tag "default_icon.png", class:"rounded-circle mt-2 ", alt:"メニュー", size:"32x32"%>
                <div class="col float-end ms-3 me-2">
                  <span class="fw-bolder"><%= current_user.username %></span>
                  <p class="text-sm-start fw-light">クリエイターページ</p>
                </div>
              </div>
            </div>
          </li>
          <li><hr class="dropdown-divider"></li>
          <li><%= button_to '自分の記事', root_path, method: :get, class:"btn btn-light w-100" %></li>
          <li><%= button_to 'スキした記事', root_path, method: :get, class:"btn btn-light w-100" %></li>
          <li><%= button_to 'ログアウト', destroy_user_session_path, method: :destroy, class:"btn btn-light w-100" %></li>
        </ul>
          

        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <!-- ログイン・登録ボタン -->
        <%= link_to "会員登録", new_user_registration_path, class: "btn btn-outline-success" %>
        <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-secondary" %>
      <% end %>
    </div>
  </div>

  <!-- メインコンテンツ -->
  <div class="row">
    <!-- サイドバー -->
    <div class="col-3">
      <ul class="list-group">
        <li class="list-group-item "><span class="text-muted">つかう</span></li>
        <li class="list-group-item"><%= link_to 'つくる', "/articles/write" %></li>
        <li class="list-group-item"><span class="text-muted">みる</span></li>
        <li class="list-group-item"><span class="text-muted">おきにいり</span></li>
      </ul>
    </div>

    <!-- 記事作成 -->
    <div class="col-9">
      <h3 class="mb-3">記事の作成</h3>
      <%= form_tag "/articles/create", method: "post" do %>
        <label for="title">タイトル</label>
        <input type="text" class="form-control me-2" name="title">
        <label for="content">コンテンツ</label>
        <textarea class="form-control me-2" name="content" rows="8" cols="50"></textarea>
        <button class="btn btn-outline-primary" type="submit">作成</button>
      <% end %>

    </div>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>