config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  #delete通信のはずなのに、getがないとエラーがおきてしまうので追加
  #devise_scope :user do
    # link_toで　method: :deleteを:destroyと勘違いしてしまっていたので注意
    # get '/users/sign_out' => 'devise/sessions#destroy'
    # post '/users/sign_out' => 'devise/sessions#destroy'
  #end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "articles#index"

  #リソースベースのルーティング（z以下リソースルーティング）を使うことで、指定のリソースコントローラでよく使われるすべてのルーティングを手軽に宣言できます。
  #resourcesを宣言するだけで、コントローラのindex、show、new、edit、create、update、destroyアクションを個別に宣言しなくても1行で宣言が完了します。
  resources :articles, param: :uuid do
    member do
      get :toggle_like
      post :toggle_like
    end
  end

  resources :categories, only: [:index] do
    collection do
      get :select
    end
  end
  resources :subcategories, only: [:show] do
    collection do
      get :select
    end
  end
  resources :messages, only: [:create]
  resources :rooms, param: :uuid, only: [:create, :show]

  resources :users, param: :uuid, only: [:index, :show, :update] do
    member do
      get :followings, :followers
    end
    resource :relationships, only: [:create, :destroy] do
      get :create
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_create :generate_uuid
  
  def to_param
    uuid
  end
  
  # Include default devise modules. Others available are:
  #  :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable,
        :confirmable, :lockable, :timeoutable

  has_one_attached :avatar, dependent: :destroy

  has_many :article, dependent: :nullify

  has_many :notification, dependent: :destroy

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  # フォローの関係,フォローした
  has_many :relationships, foreign_key: :following_id, dependent: :destroy
  # 一覧画面で使用する（あるユーザーがフォローしている人全員をとってくる）
  has_many :followings, through: :relationships, source: :follower
  
  # フォロワーの関係、フォローされた
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id, dependent: :destroy
  # 一覧画面で使用する（あるユーザーをフォローしている人全員をとってくる）
  has_many :followers, through: :reverse_of_relationships, source: :following

  # あるユーザが引数で渡されたuserにフォローされているか調べるメソッド
  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end

  validates :email, presence: true, uniqueness: { message: "このEメールはすでに使用されています" }
  validates :username, presence: true, uniqueness: { message: "このユーザー名はすでに使用されています" }
  validates :full_name, presence: true
  validates :encrypted_password, presence: true

  private

  def generate_uuid
    self.uuid = SecureRandom.hex(8)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @users=User.all
    end

    def show
        @user=User.find_by(uuid: params[:uuid])

        #相互フォローならば
        @canCreateRoom = Relationship.exists?(follower_id: current_user.id, following_id: @user.id) && Relationship.exists?(follower_id: @user.id, following_id: current_user.id)

        currentUserEntry=Entry.where(user_id: current_user.id)
        userEntry=Entry.where(user_id: @user.id)

        #同室の部屋があるかどうかの確認
        unless @user.id == current_user.id
            currentUserEntry.each do |ce|
                userEntry.each do |e|
                    if ce.room_id == e.room_id then
                        @isRoom = true
                        @room = ce.room

                        # @room.uuid = SecureRandom.hex(8)
                        # @room.save
                    end
                end
            end
            if @isRoom
            else
                @room = Room.new
                @entry = Entry.new
            end
        end
    end

    def update
    end

    def followings
        # フォローしている人の一覧
        @user = User.find_by(uuid: params[:uuid])
        @users = @user.followings
    end

    def followers
        # フォローされている人の一覧    
        @user = User.find_by(uuid: params[:uuid])
        @users = @user.followers
    end

    def mypage
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/followers.html.erb
<div class="col-md-12 border_right border_left">
  <div class="d-flex">
    <div>
      <%= link_to root_path do %>
        <i class="fa-solid fa-arrow-left arrow-left"></i>
      <% end %>
    </div>
    <div class="profile_top_name">
      <h3>
        <%= @user.username %> さんをフォローしている人
      </h3>

      <table class="table text-center">
        <thead>
          <tr>
            <th>Users</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                  <%= image_tag "default_icon.png", class:"rounded-circle mt-2 ", alt:"メニュー", size:"32x32"%>
                <% end %>
              </td>
              <td></td>
              <td>
                <%= link_to user_path(user), class: "text_deco_no" do %>
                  <%= user.username %>
                <% end %>
              </td>
              <td></td>
              <td>
                <%= link_to user_path(user), class: "text_deco_no" do %>
                  @<%= user.username %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/followings.html.erb
<div class="col-md-12 border_right border_left">
  <div class="d-flex">
    <div>
      <%= link_to root_path do %>
        <i class="fa-solid fa-arrow-left arrow-left"></i>
      <% end %>
    </div>
    <div class="profile_top_name">
      <h3>
        <%= @user.username %> さんがフォローしている人
      </h3>

      <table class="table text-center">
        <thead>
          <tr>
            <th>Users</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <% if false %><% user.icon.attached? %> 
                  <%= link_to user_path(user) do %>
                    <%= image_tag user.icon, class: "icon_img" %>
                  <% end %>
                <% else %>
                  <%= link_to user_path(user) do %>
                    <%= image_tag "default_icon.png", class:"rounded-circle mt-2 ", alt:"メニュー", size:"32x32"%>
                  <% end %>
                <% end %>
              </td>
              <td></td>
              <td>
                <%= link_to user_path(user), class: "text_deco_no" do %>
                  <%= user.username %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>フォローリスト</h1>
<h2>ようこそ <%= current_user.username %> さん！</h2>
<% @users.each do |u| %>
  <p><%= link_to u.username + "さん", user_path(u) %></p>
  <hr>
<% end %>

app/views/users/show.html.erb
<h1>ユーザー詳細</h1>
<hr>
<h2><%= @user.username %></h2>
<% if @user.avatar.attached? %>
  <%= image_tag article.user.avatar.variant(resize_to_limit: [48, 48]), class:"rounded-circle me-2" %>
<% else %>
  <%= image_tag "default_icon.png", size:"48x48", class:"rounded-circle me-2" %>
<% end %>
<div>
  自己紹介
  <br>
  <% if @user.selfIntroduction!=""%>
    <%= @user.selfIntroduction %>
  <% else %>
    
  <% end %>
  <br>
</div>
<hr>
<% if @user.id == current_user.id %>

<% else %>
  <% if @isRoom %>
    <p><%= link_to "チャットへ", room_path(@room) %>
    <% form_for @room do |f| %>
      <%= fields_for @entry do |e| %>
        <%= e.hidden_field :user_id, :value=> @user.id %>
      <% end %>
      <%= f.submit "チャットを始める", class:"btn-primary"%>
    <% end %>
  <% elsif @canCreateRoom %>
    <%= form_for @room do |f| %>
      <%= fields_for @entry do |e| %>
        <%= e.hidden_field :user_id, :value=> @user.id %>
      <% end %>
      <%= f.submit "チャットを始める", class:"btn-primary"%>
    <% end %>
  <% end %>
<% end %>

<%= link_to "ユーザー一覧に戻る", users_path %>

<div class="text-end mt-4 me-4">
  <%# もし、user.idがcurrent_userと一致しないならフォローボタンかフォロー解除ボタンを表示させる %>
  <% if current_user.id != @user.id %>
    <% if @user.is_followed_by?(current_user) %>
      <%= link_to user_relationships_path(@user), data: { "turbo-method": :delete }, class: "btn btn-outline-primary" do %>
        <%= @user.username %> をフォロー解除
      <% end %>
    <% else %>
      <%= link_to user_relationships_path(@user), data: { "turbo-method": :post }, class: "btn btn btn-primary" do %>
        <%= @user.username %> をフォロー
      <% end %>
    <% end %>
  <% end %>
</div>

<div class="d-flex relationsip">
  <div class="follow">
    <p>
      <span>
        <%= link_to @user.followings.count, followings_user_path(@user), class: "follow-link-count" %>
      </span>
      | Following
    </p>
  </div>
  <div class="follow">
    <p>
      <span>
        <%= link_to @user.followers.count, followers_user_path(@user), class: "follow-link-count" %>
      </span>
      | Followers
    </p>
  </div>
</div>