config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  #delete通信のはずなのに、getがないとエラーがおきてしまうので追加
  #devise_scope :user do
    # link_toで　method: :deleteを:destroyと勘違いしてしまっていたので注意
    # get '/users/sign_out' => 'devise/sessions#destroy'
    # post '/users/sign_out' => 'devise/sessions#destroy'
  #end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "articles#index"

  #リソースベースのルーティング（z以下リソースルーティング）を使うことで、指定のリソースコントローラでよく使われるすべてのルーティングを手軽に宣言できます。
  #resourcesを宣言するだけで、コントローラのindex、show、new、edit、create、update、destroyアクションを個別に宣言しなくても1行で宣言が完了します。
  resources :articles, param: :uuid do
    member do
      get :toggle_like
      post :toggle_like
    end
  end

  resources :categories, only: [:index] do
    collection do
      get :select
    end
  end
  resources :subcategories, only: [:show] do
    collection do
      get :select
    end
  end
  resources :messages, only: [:create]
  resources :rooms, param: :uuid, only: [:create, :show]

  resources :users, param: :uuid, only: [:index, :show, :update] do
    member do
      get :followings, :followers
    end
    resource :relationships, only: [:create, :destroy] do
      get :create
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :subcategories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories = Category.all
    end
    def select
        @categories = Category.all
        @article = Article.find_by(uuid: params[:uuid])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<% @categories.each do |category| %>
  <div>
    <%= link_to category.name, subcategory_path(category) %>
  </div>
<% end %>

app/views/categories/select.html.erb
<!-- 

<% @categories.each_with_index do |category, index| %>
  <div class="form-check">
    <% if index==0 %>
      <input class="form-check-input" type="radio" id="radio_1_<%= index %>" name="radio_1" value="<%= index %>" checked>
    <% else %>
      <input class="form-check-input" type="radio" id="radio_1_<%= index %>" name="radio_1" value="<%= index %>">
    <% end %>
    <label class="form-check-label" for="radio_1_<%= index %>">
      <%= category.name %>
    </label>
  </div>
<% end %>

-->

<h3 class="mb-3">大カテゴリの選択</h3>
<%= form_with url: select_subcategories_path, local: true, method: :get do |f| %>
  <%#= f.collection_radio_buttons :id, @categories, :id, :name, class:"form-check"%>
  <% @categories.each_with_index do |c, index| %>
    <div class="form-check">
      <%= f.radio_button :id, c.id, checked: (index==0) %>
      <%= f.label :id, c.name, for: {value: c.id}%>
    </div>
  <% end %>
  <%= f.hidden_field :article_uuid, value: @article.uuid %>
  <%= f.submit "次へ", class: "btn btn-outline-primary" %>
<% end %>