config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  #delete通信のはずなのに、getがないとエラーがおきてしまうので追加
  #devise_scope :user do
    # link_toで　method: :deleteを:destroyと勘違いしてしまっていたので注意
    # get '/users/sign_out' => 'devise/sessions#destroy'
    # post '/users/sign_out' => 'devise/sessions#destroy'
  #end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "articles#index"

  #リソースベースのルーティング（z以下リソースルーティング）を使うことで、指定のリソースコントローラでよく使われるすべてのルーティングを手軽に宣言できます。
  #resourcesを宣言するだけで、コントローラのindex、show、new、edit、create、update、destroyアクションを個別に宣言しなくても1行で宣言が完了します。
  resources :articles, param: :uuid do
    member do
      get :toggle_like
      post :toggle_like
    end
  end

  resources :categories, only: [:index] do
    collection do
      get :select
    end
  end
  resources :subcategories, only: [:show] do
    collection do
      get :select
    end
  end
  resources :messages, only: [:create]
  resources :rooms, param: :uuid, only: [:create, :show]

  resources :users, param: :uuid, only: [:index, :show, :update] do
    member do
      get :followings, :followers
    end
    resource :relationships, only: [:create, :destroy] do
      get :create
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "It Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">


    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if show_header? %>
      <div class="container my-4">
      <!-- ヘッダー -->
      <div class="d-flex justify-content-between align-items-center mb-4">
        <h1><%= link_to "I T", root_path %></h1>

        <!-- 検索フォーム 
        
        <input type="text" class="form-control d-flex me-2 w-50" placeholder="キーワードやクリエイターで検索" name="keyword">
        <%= link_to "検索", root_path, class: "btn btn-primary" %>-->

        <div class="d-flex">
          <% if user_signed_in? %>
            <button type="button" class="btn dropdown-toggle border-white text-white" id="dropdownBell" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expaneded="false">
              <span style="position: relative;">
                <%= image_tag "Bell.png", class:"rounded-circle", alt:"ベル", size:"24x24"%>
                <% if current_user.notifications_count > 9 %>
                  <span class="badge rounded-pill bg-danger" style="position: absolute; top: -10px; left: 5px;">9+</span>
                <% elsif current_user.notifications_count > 0 %>
                  <span class="badge rounded-pill bg-danger" style="position: absolute; top: -10px; left: 5px;"><%=current_user.notifications_count%></span>
                <% end %>
              </span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownBell">
              <li class="">
                通知１
              </li>
              <li><hr class="dropdown-divider"></li>
              <li class="">
                通知２
              </li>
            </ul>
            <button type="button" class="btn dropdown-toggle border-white text-white" id="dropdownMenu" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expaneded="false">
              <%= image_tag "default_icon.png", class:"rounded-circle", alt:"メニュー", size:"32x32"%>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu">
              <li class="">
                <div class="row">
                  <div class="col ms-3 mt-1 clearfix">
                    <%= image_tag "default_icon.png", class:"rounded-circle mt-2 ", alt:"メニュー", size:"32x32"%>
                    <div class="col float-end ms-3 me-2">
                      <span class="fw-bolder"><%= current_user.username %></span>
                      <p class="text-sm-start fw-light">クリエイターページ</p>
                    </div>
                  </div>
                </div>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li><%= button_to "ログアウト", destroy_user_session_path, method: :delete, class:"btn btn-light w-100" %></li>
            </ul>
              
            <%#= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
          <% else %>
            <!-- ログイン・登録ボタン -->
            <%= link_to "会員登録", new_user_registration_path, class: "btn btn-success me-2" %>
            <%= link_to "ログイン", new_user_session_path, class: "btn btn-secondary" %>
          <% end %>
        </div>
      </div>

      <!-- メインコンテンツ -->
      <div class="row">
        <!-- サイドバー -->
        <div class="col-3">
          <ul class="list-group">
            <li class="list-group-item "><span class="text-muted">つかう</span></li>
            <li class="list-group-item"><%= link_to "つくる", new_article_path %></li>
            <li class="list-group-item"><%= link_to "みる", root_path %></li>
            <li class="list-group-item"><span class="text-muted">おきにいり</span></li>
            <li class="list-group-item"><%= link_to "フォローする", users_path %></li>
            <li class="list-group-item"><%= link_to "カテゴリ", categories_path %></li>
          </ul>
        </div>

        <div class="col-9">
          <%= yield %>
        </div>
        
      </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <% else %>
      <%= yield %>
    <% end %>
  </body>

</html>